In [2]:
import numpy as np
T1=0
T2=0 
T3=0 
T4=0 
T5=0 


In [3]:
T1 = (T1/180.0)*np.pi
T2 = (T2/180.0)*np.pi
T3 = (T3/180.0)*np.pi
T4 = (T4/180.0)*np.pi
T5 = (T5/180.0)*np.pi

In [4]:
R0_1 = [[np.cos(T1),0,np.sin(T1)],
        [np.sin(T1),0,-np.cos(T1)],
        [0,1,0]]

R1_2 = [[np.cos(T2),-np.sin(T2),0],
        [np.sin(T2),np.cos(T2),0],
        [0,0,1]]

R2_3 = [[np.cos(T3),-np.sin(T3),0],
        [np.sin(T3),np.cos(T3),0],
        [0,0,1]]

R3_4 = [[-np.sin(T4),0,np.cos(T4)],
        [np.cos(T4),0,np.sin(T4)],
        [0,1,0]]

R4_5 = [[np.cos(T5),-np.sin(T5),0],
        [np.sin(T5),np.cos(T5),0],
        [0,0,1]]

In [5]:
R0_2 = np.dot(R0_1,R1_2)
R2_4 = np.dot(R2_3,R3_4)
R4_5 = R4_5

In [6]:
R0_4 = np.dot(R0_2,R2_4)
R0_5 = np.dot(R0_4,R4_5)

In [7]:
print("\nR0_1-->")
print(np.matrix(R0_1))

print("\nR1_2-->")
print(np.matrix(R1_2))

print("\nR2_3-->")
print(np.matrix(R2_3))

print("\nR3_4-->")
print(np.matrix(R3_4))

print("\nR4_5-->")
print(np.matrix(R4_5))


R0_1-->
[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]

R1_2-->
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

R2_3-->
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

R3_4-->
[[-0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]

R4_5-->
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
print("\nR0_5-->")
print(np.matrix(R0_5))


R0_5-->
[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 1.  0.  0.]]


## From here the displacement is taking place 

In [9]:
a1 = 170.5
a2 = 83
a3 = 83
a4 = 72.5
a5 = 116

In [10]:
d0_1=[[0],[0],[170.5]]
d1_2= [[a2*np.cos(T2)],[a2*np.sin(T2)],[0]]
d2_3=[[a3*np.cos(T3)],[a3*np.sin(T3)],[0]]
d3_4 = [[0],[0],[0]]
d4_5 = [[0],[0],[a4+a5]]

In [11]:
H0_1 = np.concatenate((R0_1,d0_1),1)
H0_1 = np.concatenate((H0_1,[[0,0,0,1]]),0)

H1_2 = np.concatenate((R1_2,d1_2),1)
H1_2 = np.concatenate((H1_2,[[0,0,0,1]]),0)

H2_3 = np.concatenate((R2_3,d2_3),1)
H2_3 = np.concatenate((H2_3,[[0,0,0,1]]),0)

H3_4 = np.concatenate((R3_4,d3_4),1)
H3_4 = np.concatenate((H3_4,[[0,0,0,1]]),0)

H4_5 = np.concatenate((R4_5,d4_5),1)
H4_5 = np.concatenate((H4_5,[[0,0,0,1]]),0)

In [12]:
H0_2 = np.dot(H0_1,H1_2)
H2_4 = np.dot(H2_3,H3_4)
H4_5 = H4_5

In [13]:
H0_4 = np.dot(H0_2,H2_4)
H0_5 = np.dot(H0_4,H4_5)

In [14]:
print(np.matrix(H0_5))

[[  0.    0.    1.  354.5]
 [  0.   -1.    0.    0. ]
 [  1.    0.    0.  170.5]
 [  0.    0.    0.    1. ]]


In [15]:
import numpy as np
from numpy import cos, sin

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

import sympy as sp
from sympy import pi


In [16]:
DOF = 5
q1, q2, q3, q4, q5 = sp.symbols('q1 q2 q3 q4 q5')

# Value of pi from the symbolic library for convenience
spi = sp.pi
DH_params = []

DH_params.append([q1,pi/2,0,170.5])
DH_params.append([q2,0,83,0])
DH_params.append([q3, 0, 83, 0])
DH_params.append([q4+(pi/2),pi/2, 0, 0])
DH_params.append([q5, 0, 0, 188.5])

DH_params

[[q1, pi/2, 0, 170.5],
 [q2, 0, 83, 0],
 [q3, 0, 83, 0],
 [q4 + pi/2, pi/2, 0, 0],
 [q5, 0, 0, 188.5]]

In [17]:
DH_params[0]

[q1, pi/2, 0, 170.5]

In [18]:
def DH_trans_matrix(params):
    
    theta, alpha, a, d = (params[0], params[1], params[2], params[3])
    
    mat = sp.Matrix([[sp.cos(theta), -1*sp.sin(theta)*sp.cos(alpha), sp.sin(theta)*sp.sin(alpha),    a*sp.cos(theta)],
                    [sp.sin(theta), sp.cos(theta)*sp.cos(alpha),    -1*sp.cos(theta)*sp.sin(alpha), a*sp.sin(theta)],
                    [0,             sp.sin(alpha),                  sp.cos(alpha),                  d],
                    [0,             0,                              0,                              1]])
    
    return mat

In [19]:
H0_1_exp = DH_trans_matrix(DH_params[0])
H0_1_exp = H0_1_exp.subs(q1,0)
H0_1_exp, H0_1

(Matrix([
 [1, 0,  0,     0],
 [0, 0, -1,     0],
 [0, 1,  0, 170.5],
 [0, 0,  0,     1]]),
 array([[  1. ,   0. ,   0. ,   0. ],
        [  0. ,   0. ,  -1. ,   0. ],
        [  0. ,   1. ,   0. , 170.5],
        [  0. ,   0. ,   0. ,   1. ]]))

In [20]:
H1_2_exp = DH_trans_matrix(DH_params[1])
# H1_2_exp = H1_2_exp.subs(q2,0)
H1_2_exp

Matrix([
[cos(q2), -sin(q2), 0, 83*cos(q2)],
[sin(q2),  cos(q2), 0, 83*sin(q2)],
[      0,        0, 1,          0],
[      0,        0, 0,          1]])

In [21]:
H2_3_exp = DH_trans_matrix(DH_params[2])
# H1_2_exp = H1_2_exp.subs(q2,0)
H2_3_exp

Matrix([
[cos(q3), -sin(q3), 0, 83*cos(q3)],
[sin(q3),  cos(q3), 0, 83*sin(q3)],
[      0,        0, 1,          0],
[      0,        0, 0,          1]])

In [22]:
H3_4_exp = DH_trans_matrix(DH_params[3])
# H1_2_exp = H1_2_exp.subs(q2,0)
H3_4_exp

Matrix([
[-sin(q4), 0, cos(q4), 0],
[ cos(q4), 0, sin(q4), 0],
[       0, 1,       0, 0],
[       0, 0,       0, 1]])

In [23]:
H4_5_exp = DH_trans_matrix(DH_params[4])
# H1_2_exp = H1_2_exp.subs(q2,0)
H4_5_exp

Matrix([
[cos(q5), -sin(q5), 0,     0],
[sin(q5),  cos(q5), 0,     0],
[      0,        0, 1, 188.5],
[      0,        0, 0,     1]])

In [24]:
H0_5_exp = H0_1_exp * H1_2_exp * H2_3_exp * H3_4_exp * H4_5_exp

In [25]:
H0_5_exp

Matrix([
[(-(-sin(q2)*sin(q3) + cos(q2)*cos(q3))*sin(q4) + (-sin(q2)*cos(q3) - sin(q3)*cos(q2))*cos(q4))*cos(q5), -(-(-sin(q2)*sin(q3) + cos(q2)*cos(q3))*sin(q4) + (-sin(q2)*cos(q3) - sin(q3)*cos(q2))*cos(q4))*sin(q5), (-sin(q2)*sin(q3) + cos(q2)*cos(q3))*cos(q4) + (-sin(q2)*cos(q3) - sin(q3)*cos(q2))*sin(q4),        188.5*(-sin(q2)*sin(q3) + cos(q2)*cos(q3))*cos(q4) + 188.5*(-sin(q2)*cos(q3) - sin(q3)*cos(q2))*sin(q4) - 83*sin(q2)*sin(q3) + 83*cos(q2)*cos(q3) + 83*cos(q2)],
[                                                                                              -sin(q5),                                                                                                -cos(q5),                                                                                           0,                                                                                                                                                                     0],
[  ((-sin(q2)*sin(q3) + cos(q2)*cos(q3))*cos(q4) 

In [26]:
H0_5_exp = H0_5_exp.subs(q1, 0)
H0_5_exp = H0_5_exp.subs(q2, 0)
H0_5_exp = H0_5_exp.subs(q3, 0)
H0_5_exp = H0_5_exp.subs(q4, 0)
H0_5_exp = H0_5_exp.subs(q5, 0)

In [27]:
type(H0_5_exp)

sympy.matrices.dense.MutableDenseMatrix

In [28]:
H0_2_exp = H0_1_exp * H1_2_exp
sp.pprint(H0_2_exp)
# H2_4 = np.dot(H2_3,H3_4)
# H4_5 = H4_5

⎡cos(q₂)  -sin(q₂)  0       83⋅cos(q₂)    ⎤
⎢                                         ⎥
⎢   0        0      -1          0         ⎥
⎢                                         ⎥
⎢sin(q₂)  cos(q₂)   0   83⋅sin(q₂) + 170.5⎥
⎢                                         ⎥
⎣   0        0      0           1         ⎦


In [29]:
_H0_1 = DH_trans_matrix(DH_params[0])
_H1_2 = DH_trans_matrix(DH_params[1])
_H2_3 = DH_trans_matrix(DH_params[2])
_H3_4 = DH_trans_matrix(DH_params[3])
_H4_5 = DH_trans_matrix(DH_params[4])

# H0_5 = H0_1 * H1_2 * H2_3 * H3_4 * H4_5


In [30]:
_H0_2 = _H0_1 * _H1_2
_H0_2

Matrix([
[cos(q1)*cos(q2), -sin(q2)*cos(q1),  sin(q1), 83*cos(q1)*cos(q2)],
[sin(q1)*cos(q2), -sin(q1)*sin(q2), -cos(q1), 83*sin(q1)*cos(q2)],
[        sin(q2),          cos(q2),        0, 83*sin(q2) + 170.5],
[              0,                0,        0,                  1]])

In [31]:
_H0_2_subs=_H0_2.subs(q1,0)
_H0_2_subs=_H0_2_subs.subs(q2,0)
_H0_2_subs

Matrix([
[1, 0,  0,    83],
[0, 0, -1,     0],
[0, 1,  0, 170.5],
[0, 0,  0,     1]])

In [32]:
H0_2

array([[  1. ,   0. ,   0. ,  83. ],
       [  0. ,   0. ,  -1. ,   0. ],
       [  0. ,   1. ,   0. , 170.5],
       [  0. ,   0. ,   0. ,   1. ]])

In [33]:

_H2_4 = _H2_3 * _H3_4
_H2_4

Matrix([
[-sin(q3)*cos(q4) - sin(q4)*cos(q3), 0, -sin(q3)*sin(q4) + cos(q3)*cos(q4), 83*cos(q3)],
[-sin(q3)*sin(q4) + cos(q3)*cos(q4), 0,  sin(q3)*cos(q4) + sin(q4)*cos(q3), 83*sin(q3)],
[                                 0, 1,                                  0,          0],
[                                 0, 0,                                  0,          1]])

In [34]:
_H2_4_subs=_H2_4.subs(q3,0)
_H2_4_subs=_H2_4_subs.subs(q4,0)
_H2_4_subs

Matrix([
[0, 0, 1, 83],
[1, 0, 0,  0],
[0, 1, 0,  0],
[0, 0, 0,  1]])

In [35]:
H2_4

array([[ 0.,  0.,  1., 83.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [36]:
# H0_4 = np.dot(H0_2,H2_4)
# H0_5 = np.dot(H0_4,H4_5)
_H0_5 = _H0_1 * _H1_2 * _H2_3 * _H3_4 * _H4_5
_H0_5

Matrix([
[(-(-sin(q2)*sin(q3)*cos(q1) + cos(q1)*cos(q2)*cos(q3))*sin(q4) + (-sin(q2)*cos(q1)*cos(q3) - sin(q3)*cos(q1)*cos(q2))*cos(q4))*cos(q5) + sin(q1)*sin(q5), -(-(-sin(q2)*sin(q3)*cos(q1) + cos(q1)*cos(q2)*cos(q3))*sin(q4) + (-sin(q2)*cos(q1)*cos(q3) - sin(q3)*cos(q1)*cos(q2))*cos(q4))*sin(q5) + sin(q1)*cos(q5), (-sin(q2)*sin(q3)*cos(q1) + cos(q1)*cos(q2)*cos(q3))*cos(q4) + (-sin(q2)*cos(q1)*cos(q3) - sin(q3)*cos(q1)*cos(q2))*sin(q4), 188.5*(-sin(q2)*sin(q3)*cos(q1) + cos(q1)*cos(q2)*cos(q3))*cos(q4) + 188.5*(-sin(q2)*cos(q1)*cos(q3) - sin(q3)*cos(q1)*cos(q2))*sin(q4) - 83*sin(q2)*sin(q3)*cos(q1) + 83*cos(q1)*cos(q2)*cos(q3) + 83*cos(q1)*cos(q2)],
[(-(-sin(q1)*sin(q2)*sin(q3) + sin(q1)*cos(q2)*cos(q3))*sin(q4) + (-sin(q1)*sin(q2)*cos(q3) - sin(q1)*sin(q3)*cos(q2))*cos(q4))*cos(q5) - sin(q5)*cos(q1), -(-(-sin(q1)*sin(q2)*sin(q3) + sin(q1)*cos(q2)*cos(q3))*sin(q4) + (-sin(q1)*sin(q2)*cos(q3) - sin(q1)*sin(q3)*cos(q2))*cos(q4))*sin(q5) - cos(q1)*cos(q5), (-sin(q1)*sin(q2)*sin(q3) + s

In [37]:
_H0_5_subs = _H0_5.subs(q1,0)
_H0_5_subs = _H0_5_subs.subs(q2,0)
_H0_5_subs = _H0_5_subs.subs(q3,0)
_H0_5_subs = _H0_5_subs.subs(q4,0)
_H0_5_subs = _H0_5_subs.subs(q5,0)
_H0_5_subs

Matrix([
[0,  0, 1, 354.5],
[0, -1, 0,     0],
[1,  0, 0, 170.5],
[0,  0, 0,     1]])

In [38]:
H0_5

array([[  0. ,   0. ,   1. , 354.5],
       [  0. ,  -1. ,   0. ,   0. ],
       [  1. ,   0. ,   0. , 170.5],
       [  0. ,   0. ,   0. ,   1. ]])